sentence = input("Enter you sentence :")
print("Your sentence is :",sentence)
word1= input("Enter the word which need to be replaced: ")
word2 =input("Enter the word to be replaced with: ")
print(sentence.replace(word1,word2))