name=input("Input you name")
age=input("input you age")
print("Your name is "+name +" and your age is" + age + "years old")
name=str(input("Input your name: "))
age= int(input("enter your age "))
print("Your name is "+name+ "and your age is ",age)